version: '3.8'

services:
  mooc-api:
    build: .
    ports:
      - 8080:8080
    environment:
      MOOC_HOST: 0.0.0.0
      MOOC_DBHOST: mysql

  mysql:
    image: mysql:8.0.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: backoffice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql_data: